keys:
  - &yubikey E6028682743BF174D2E5B3AF92810374E3AC1EE1
  - &zenbook age16dtszcmd8thqphvm2tr4vutq2va65qkhap7pt7d3402gknkr4dfswhgemd
  - &framework age1m8lwm02q3xxhqt0lzz4xfxrlx398vg6pdfe9hemrmjy2mgx0h4pqjx6u4z
  - &omen age1e5qcyhvtszeullyzm7tnrhc22h4h03yvt8etkpvkucl4m56tza8spr0jvh
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        - *yubikey # This is used to edit file on new hosts
        age:
        - *zenbook # This is used during build, as sudo cannot access yubikey gpg keys
        - *framework
        - *omen
