[
    ./bufferline.lua
    ./completions.lua
    ./dap.lua
    ./enable.lua
    ./git.lua
    ./icons.lua
    ./lspconfig.lua
    ./lualine.lua
    ./telescope.lua
    ./treesitter.lua
    ./treesitter-context.lua
]
