#!/usr/bin/env bash

# get PID of the focused window
tree=$(swaymsg -t get_tree | jq '.. | select(.focused? == true)')
pid=$(swaymsg -t get_tree | jq '.. | select(.focused? == true).pid')

echo "TREE: $tree"
echo "PID: $pid"

# fallback dir = $HOME
dir=$HOME

if [ -n "$pid" ]; then
    # climb up the process tree until we find a process with a cwd
    while [ "$pid" -ne 1 ]; do
        if [ -d "/proc/$pid/cwd" ]; then
            dir=$(readlink -f "/proc/$pid/cwd")
            break
        fi
        pid=$(ps -o ppid= -p "$pid")
    done
fi

echo "DIR: $dir"

exec kitty --directory "$dir"
